site_name: harveyitismedocs
site_url: https://harveyitismedocs.com
nav:
 - Home: index.md
 - About: about.md
 - Home Automation: 
    - Home Assistant Getting Started: home-automation/home_assistant_getting_started.md
 - Data Engineering: data_engineering.md

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
